List<dynamic> foodsCategory = [
  "burger",
  "fries",
  "sandwich",
  "drink",
];

List<dynamic> meals = [
  "beefburger",
  "fastmeal",
  "shawarma",
];


List<dynamic> foodInfo = [
  {
    "type": "burger",
    "name": "Beef Burger",
    "img": "assets/images/burger/beefburger.png",
    "price": 18,
    "rate": 4.5,
    "numOfItem": 1,
    "total price": 18,
  },
  {
    "type": "burger",
    "name": "Chicken Burger",
    "img": "assets/images/burger/chikenburger.png",
    "price": 18,
    "rate": 4.5,
    "numOfItem": 1,
    "total price": 18,
  },
  {
    "type": "burger",
    "name": "Cheese Burger",
    "img": "assets/images/burger/cheesburger.png",
    "price": 20,
    "rate": 4.5,
    "numOfItem": 1,
    "total price": 20,
  },
  {
    "type": "burger",
    "name": "Double Beef Burger",
    "img": "assets/images/burger/doubleBburger.png",
    "price": 23,
    "rate": 4.5,
    "numOfItem": 1,
    "total price": 23,
  },
  {
    "type": "burger",
    "name": "Double Chicken Burger",
    "img": "assets/images/burger/doubleCburger.png",
    "price": 23,
    "rate": 4.5,
    "numOfItem": 1,
    "total price": 23,
  },
  {
    "type": "sandwich",
    "name": "Classic Hotdog Sandwich",
    "img": "assets/images/sandwich/classic_hotdog.png",
    "price": 10,
    "rate": 4.5,
    "numOfItem": 1,
    "total price": 10,
  },
  {
    "type": "sandwich",
    "name": "King Hotdog Sandwich",
    "img": "assets/images/sandwich/double_hotdog.png",
    "price": 14,
    "rate": 4.5,
    "numOfItem": 1,
    "total price": 14,
  },
  {
    "type": "sandwich",
    "name": "Classic Sandwich",
    "img": "assets/images/sandwich/sandwich.png",
    "price": 7,
    "rate": 4.5,
    "numOfItem": 1,
    "total price": 7,
  },
  {
    "type": "sandwich",
    "name": " Shawarma Sandwich",
    "img": "assets/images/sandwich/shawarma.png",
    "price": 7,
    "rate": 4.5,
    "numOfItem": 1,
    "total price": 7,
  },
  {
    "type": "fries",
    "name": "Fries",
    "img": "assets/images/fries/fries.png",
    "price": 5,
    "rate": 4.5,
    "numOfItem": 1,
    "total price": 5,
  },
  {
    "type": "drinks",
    "name": "Coca cola Soda",
    "img": "assets/images/drinks/drink.png",
    "price": 3,
    "rate": 4.5,
    "numOfItem": 1,
    "total price": 3,
  },
  {
    "type": "drinks",
    "name": "Apple Soda",
    "img": "assets/images/drinks/apple_drink.png",
    "price": 3,
    "rate": 4.5,
    "numOfItem": 1,
    "total price": 3,
  },
];

List<dynamic> mealsInfo = [
  {
    "type": "meals",
    "name": "Beef Burger Meal",
    "img": "assets/images/meals/beefburger.png",
    "price": 30,
    "rate": 4.5,
    "numOfItem": 1,
    "total price": 30,
  },
  {
    "type": "meals",
    "name": "Fast Meal",
    "img": "assets/images/meals/fastmeal.png",
    "price": 20,
    "rate": 4.5,
    "numOfItem": 1,
    "total price": 20,
  },
  {
    "type": "meals",
    "name": "shawarma Meal",
    "img": "assets/images/meals/shawarma.png",
    "price": 18,
    "rate": 4.5,
    "numOfItem": 1,
    "total price": 18,
  },
];